language: node_js
node_js:
  - "6"
  - "lts/*"
  - "node"
cache: yarn
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
script:
  - yarn build
  - yarn test
  - yarn coverage-publish
